language: node_js
node_js:
  - "16"
# Specify the operating system
os:
  - linux
  - osx
# Cache dependencies
cache:
  directories:
    - node_modules

# Install dependencies
install:
  - npm ci

# Run tests
script:
  - npm run test
  - npm run build

# Deploy to npm
deploy:
  provider: npm
  email: "sergiosantosmenaq@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: main
# Notifications
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
      - secure: "encrypted-slack-webhook-url"